[tools]
python = "3.13"
uv = "0.6.12"
"aqua:evilmartians/lefthook" = "1.11.6"

[env]
_.python.venv = { path = ".venv", create = true, uv_create_args = ["--seed"] }

[tasks.setup]
description = "Install dependencies and setup environment"
run = [
  "uv pip compile --extra dev pyproject.toml > requirements.txt",
  "uv pip install -r requirements.txt",
  "pnpm i",
  "lefthook install"
]

[tasks.check]
description = "Run all code checks"
depends = ["check:be", "check:fe"]

[tasks."check:be"]
description = "Run backend code checks"
run = [
  "mypy backend/"
]

[tasks."check:fe"]
description = "Run frontend code checks"
run = [
  "pnpm --silent --filter=./apps/www typecheck",
  "pnpm biome check --diagnostic-level=warn --write --unsafe ."
]

[tasks.dev]
description = "Start all development services"
depends = ["dev:be", "dev:fe --name=www"]

[tasks."dev:be"]
description = "Start backend development services"
dir = "{{config_root}}/backend"
run = [
  "flask --debug run"
]

[tasks."dev:fe"]
description = "Start frontend development services"
run = [
  'pnpm --silent --filter=./apps/{{option(name="name", default="www")}} dev'
]

[tasks.format]
description = "Format files"
run = [
  "ruff format backend/",
  "pnpm biome format . --write"
]
